### ISSUE TITLE
QA_VLSI_Schematic Design Of D-Latch and D-Flip Flop_Experiment_not-ported-properly

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/vlsi-iiith#108]
Defect Description :
In the experiment section of Schematic Design Of D-Latch and D-Flip Flop experiment, Instead of porting the experiment using iframe, ported in text editor using HTML component. Due to this the experiment is not working.

Actual Result :
In the experiment section of Schematic Design Of D-Latch and D-Flip Flop experiment, Instead of porting the experiment using iframe, ported in text editor using HTML component. Due to this the experiment is not working.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
Not available

**Comment by BSravanthi** [comment]
Removed the existing unit and ported the experiment using Iframe tool.

**Comment by sravanthimodepu** [comment]
Closing.
