### ISSUE TITLE
QA_Layout Design_Usability_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#11]
Defect Description :
In the home page/landing page of "Layout Design" experiment, an extra header link is present in the page where the extra header link should be removed as it is not required       

Actual Result :
In the home page/landing page of "Layout Design" experiment, an extra header link is present in the page   

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Layout%20Design/Layout%20Design_01_Usability_smk.org

Attachment:
![7](https://cloud.githubusercontent.com/assets/14869397/14706011/f30e20b0-07d9-11e6-82ea-73c415b8a83a.png)

**Comment by sadhanareddy** [comment]
issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #11
