### ISSUE TITLE
QA_VLSI_Schematic Design Of D-Latch and D-Flip Flop_Manual_no-content-is-found

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/vlsi-iiith#111]
Defect Description
In the Manual section of Schematic Design Of D-Latch and D-Flip Flop experiment, found no content.

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments
Not available

**Comment by BSravanthi** [comment]
Removed the Manual section as could not find the source from vlab.co.in.

**Comment by sravanthimodepu** [comment]
Closing.
