### ISSUE TITLE
QA_VLSI_Schematic Design Of D-Latch and D-Flip Flop_Quizzes_improper-porting

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/vlsi-iiith#112]
Defect Description
In the Quizzes section of Schematic Design Of D-Latch and D-Flip Flop experiment in VLSI lab, the questions are not ported properly. Ported using text editor from HTML component, instead of porting in Problem component. Due to this the functionality of the quiz section is not proper.

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments
Not available

**Comment by BSravanthi** [comment]
The quiz section was ported using Text editor of HTML component. Removed the quiz section and ported the questions using Problem component.

**Comment by sravanthimodepu** [comment]
Closing.
