### ISSUE TITLE
QA_VLSI_Spice Code Platform_Simulator_text-wrapped-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/vlsi-iiith#114]
Defect Description
While testing in Windows machine found that the content in the small screen of simulator section is wrapped due to improper alignment. Due to this the user is unable to get the content of the experiment.

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments
Not available.

**Comment by BSravanthi** [comment]
Corrected the alignment.

**Comment by sravanthimodepu** [comment]
Closing.
