### ISSUE TITLE
QA_VLSI_Spice Code Platform_Quizzes_improper-porting

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/vlsi-iiith#116]
Defect Description
In the Quizzes section of Spice Code Platform experiment in VLSI lab, the questions are not ported properly. Ported using text editor from HTML component, instead of porting in Problem component. Due to this the functionality of the quiz section is not proper. 
The Post and Pre quiz sections are ported in one unit itself. Instead both the sections should be ported in separate units.

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments
Not available

**Comment by BSravanthi** [comment]
The quiz section was ported using Text editor of HTML component. Removed the quiz section and ported the questions using Problem component.
Ported both pre and post quizzes in separate units.

**Comment by sravanthimodepu** [comment]
Closing.
