### ISSUE TITLE
QA_VLSI_Spice Code Platform_Quiz_Spelling mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/vlsi-iiith#117]
Defect Description
In the Quizzes page of the Spice Code Platform experiment in this lab, found spelling mistakes.

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments
Not available

**Comment by BSravanthi** [comment]
Corrected spelling mistakes

**Comment by sravanthimodepu** [comment]
Closing.
