### ISSUE TITLE
QA_Layout Design_Usability_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#12]
Defect Description :
In the landing page/home page of "Layout Design" experiment, the name of the experiment is not present in the screen instead the experiment name should be displayed on the screen at the top of the header options       

Actual Result :
In the landing page/home page of "Layout Design" experiment, the name of the experiment is not present in the screen  

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Layout%20Design/Layout%20Design_01_Usability_smk.org

Attachment:
![8](https://cloud.githubusercontent.com/assets/14869397/14706028/031ebb7c-07da-11e6-99e7-f70f8739a52b.png)

**Comment by sadhanareddy** [comment]
issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #12
