### ISSUE TITLE
QA_VLSI_Layout Design_Quizzes_given-quiz-link-instead-of-porting

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/vlsi-iiith#131]
Defect Description
In the Quizzes section of Layout Design experiment in VLSI lab, the questions are not ported properly. Given a link that redirects to vlabs VLSI quizzes page is given using text editor from HTML component, instead of porting in Problem component. Due to this the functionality of the quiz section is not proper.

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments
Not available

**Comment by BSravanthi** [comment]
Removed the quiz section and ported the questions using Problem component.

**Comment by BSravanthi** [comment]
Check button functionality is improper

**Comment by sravanthimodepu** [comment]
Numbering is missing for the quiz questions. Hence reopening the issue.
