### ISSUE TITLE
QA_Spice Code Platform_Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#25]
Defect Description :
In the "Spice Code Platform" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen inorder to view the list of experiments by the user   

Actual Result :
In the "Spice Code Platform" experiment,the back to experiments link is not present in the page

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Spice%20Code%20Platform/Spice%20Code%20Platform_26_Back%20to%20experiment_smk.org

Attachment:
![21](https://cloud.githubusercontent.com/assets/14869397/14732270/af1bb668-0876-11e6-8572-754fdaa54c74.png)

**Comment by sadhanareddy** [comment]
issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #25
