### ISSUE TITLE
QA_Spice Code Platform_Feedback_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#26]
Defect Description :
In the feedback page of "Spice Code Platform" experiment,when we click on submit button with out entering the data in the corresponding fields an successful message is displayed on the screen instead an error message should be displayed on the screen as to enter the data in the corresponding fields 

Actual Result :
In the feedback page of "Spice Code Platform" experiment,when we click on submit button with out entering the data in the corresponding fields an successful message is displayed on the screen

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Spice%20Code%20Platform/Spice%20Code%20Platform_24_Feedback_p1.org

Attachment:
![22](https://cloud.githubusercontent.com/assets/14869397/14732276/c67d4128-0876-11e6-993a-e25017202321.png)

**Comment by sadhanareddy** [comment]
Issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #26
