### ISSUE TITLE
QA_Spice Code Platform_Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#27]
Defect Description :
In the feedback page of "Spice Code Platform" experiment,the cancel button is not present in the page instead the cancel button should be displayed on the screen as to unselect the selected radio buttons 

Actual Result :
In the feedback page of "Spice Code Platform" experiment,the cancel button is not present in the page

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Spice%20Code%20Platform/Spice%20Code%20Platform_21_Feedback_smk.org

Attachment:
![23](https://cloud.githubusercontent.com/assets/14869397/14732289/df43274a-0876-11e6-8b7e-253995291038.png)

**Comment by sadhanareddy** [comment]
There are only two radio buttons. So, there is no need to provide a cancel button to unselect the radio buttons. Also, we are not in a process of modifying the feedback page. Hence differing this issue.

**Comment by BSravanthi** [comment]
Closed #27
