### ISSUE TITLE
QA_Spice Code Platform_Post-Quiz_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#28]
Defect Description :
In the quiz page of "Spice Code Platform" experiment, for the post quiz, the cancel button is not present in the page instead the cancel button should be displayed on the screen as to unselect the selected radio buttons 

Actual Result :
In the quiz page of "Spice Code Platform" experiment, for the post quiz, the cancel button is not present in the page
Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Spice%20Code%20Platform/Spice%20Code%20Platform_16_Post-Quiz_p1.org

Attachment:
![24](https://cloud.githubusercontent.com/assets/14869397/14732295/f5dab9c8-0876-11e6-81af-aa5a0dccb43b.png)

**Comment by sadhanareddy** [comment]
Issue is resolved now. Provided a reset button to unselect the radio buttons of the Quiz.

**Comment by BSravanthi** [comment]
Closed #28
