### ISSUE TITLE
QA_Spice Code Platform_Usability_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#29]
Defect Description :
In the home page/landing page of "Spice Code Platform" experiment, an extra header link is present in the page where the extra header link should be removed as it is not required  

Actual Result :
In the home page/landing page of "Spice Code Platform" experiment, an extra header link is present in the page 

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Spice%20Code%20Platform/Spice%20Code%20Platform_01_Usability_smk.org

**Comment by sadhanareddy** [comment]
issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #29
