### ISSUE TITLE
QA_Spice Code Platform_Usability_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#30]
Defect Description :
In the landing page/home page of "Spice Code Platform" experiment, the name of the experiment is not present in the screen instead the experiment name should be displayed on the screen at the top of the header options  

Actual Result :
In the landing page/home page of "Spice Code Platform" experiment, the name of the experiment is not present in the screen

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Spice%20Code%20Platform/Spice%20Code%20Platform_01_Usability_smk.org

Attachment:
![26](https://cloud.githubusercontent.com/assets/14869397/14732317/3046cb7e-0877-11e6-8c52-614c891f5459.png)

**Comment by sadhanareddy** [comment]
issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #30
