### ISSUE TITLE
QA_Schematic Design Of D-Latch and D-Flip Flop_Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#31]
Defect Description :
In the "Schematic Design Of D-Latch and D-Flip Flop" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen inorder to view the list of experiments by the user   

Actual Result :
In the "Schematic Design Of D-Latch and D-Flip Flop" experiment,the back to experiments link is not present in the page

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Schematic%20Design%20Of%20D-Latch%20and%20D-Flip%20Flop/Schematic%20Design%20Of%20D-Latch%20and%20D-Flip%20Flop_34_Back%20to%20experiment_smk.org

Attachment:
![27](https://cloud.githubusercontent.com/assets/14869397/14732325/4d5abcd4-0877-11e6-928c-1ea70ee41495.png)

**Comment by sadhanareddy** [comment]
issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #31
