### ISSUE TITLE
QA_Schematic Design Of D-Latch and D-Flip Flop_Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#33]
Defect Description :
In the feedback page of "Schematic Design Of D-Latch and D-Flip Flop" experiment,the cancel button is not present in the page instead the cancel button should be displayed on the screen as to unselect the selected radio buttons 

Actual Result :
In the feedback page of "Schematic Design Of D-Latch and D-Flip Flop" experiment,the cancel button is not present in the page

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Schematic%20Design%20Of%20D-Latch%20and%20D-Flip%20Flop/Schematic%20Design%20Of%20D-Latch%20and%20D-Flip%20Flop_29_Feedback_smk.org

Attachment:
![29](https://cloud.githubusercontent.com/assets/14869397/14732342/7cfe683c-0877-11e6-9f25-ad31f51b64d2.png)

**Comment by sadhanareddy** [comment]
There are only two radio buttons. So, there is no need to provide a cancel button to unselect the radio buttons. Also, we are not in a process of modifying the feedback page. Hence differing this issue.

**Comment by BSravanthi** [comment]
Closed #33
