### ISSUE TITLE
QA_Schematic Design Of D-Latch and D-Flip Flop_Usability_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#36]
Defect Description :
In the home page/landing page of "Schematic Design Of D-Latch and D-Flip Flop" experiment, an extra header link is present in the page where the extra header link should be removed as it is not required 

Actual Result :
In the home page/landing page of "Schematic Design Of D-Latch and D-Flip Flop" experiment, an extra header link is present in the page  

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Schematic%20Design%20Of%20D-Latch%20and%20D-Flip%20Flop/Schematic%20Design%20Of%20D-Latch%20and%20D-Flip%20Flop_01_Usability_smk.org

Attachment:
![32](https://cloud.githubusercontent.com/assets/14869397/14732382/e0562bcc-0877-11e6-8247-1f18fd42b47a.png)

**Comment by sadhanareddy** [comment]
issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #36
