### ISSUE TITLE
QA_Schematic Design Of D-Latch and D-Flip Flop_Usability_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#37]
Defect Description :
In the landing page/home page of "Schematic Design Of D-Latch and D-Flip Flop" experiment, the name of the experiment is not present in the screen instead the experiment name should be displayed on the screen at the top of the header options  

Actual Result :
In the landing page/home page of "Schematic Design Of D-Latch and D-Flip Flop" experiment, the name of the experiment is not present in the screen 

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Schematic%20Design%20Of%20D-Latch%20and%20D-Flip%20Flop/Schematic%20Design%20Of%20D-Latch%20and%20D-Flip%20Flop_01_Usability_smk.org

Attachment:
![33](https://cloud.githubusercontent.com/assets/14869397/14732421/43b59266-0878-11e6-84da-eab3dfbb6de6.png)

**Comment by sadhanareddy** [comment]
issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #37
