### ISSUE TITLE
QA_Delay Estimation In Chain Of Inverters_Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#38]
Defect Description :
In the "Delay Estimation In Chain Of Inverters" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen inorder to view the list of experiments by the user  

Actual Result :
In the "Delay Estimation In Chain Of Inverters" experiment,the back to experiments link is not present in the page 

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Delay%20Estimation%20In%20Chain%20Of%20Inverters/Delay%20Estimation%20In%20Chain%20Of%20Inverters_30_Back%20to%20experiment_smk.org

Attachment:
![34](https://cloud.githubusercontent.com/assets/14869397/14732435/5a5ed77a-0878-11e6-9a8b-d567e3e363d5.png)

**Comment by sadhanareddy** [comment]
issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #38
