### ISSUE TITLE
QA_Delay Estimation In Chain Of Inverters_Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#40]
Defect Description :
In the feedback page of "Delay Estimation In Chain Of Inverters" experiment,the cancel button is not present in the page instead the cancel button should be displayed on the screen as to unselect the selected radio buttons

Actual Result :
In the feedback page of "Delay Estimation In Chain Of Inverters" experiment,the cancel button is not present in the page 

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Delay%20Estimation%20In%20Chain%20Of%20Inverters/Delay%20Estimation%20In%20Chain%20Of%20Inverters_25_Feedback_smk.org

Attachment:
![36](https://cloud.githubusercontent.com/assets/14869397/14732448/85b57c6c-0878-11e6-8de7-c18101d01deb.png)

**Comment by sadhanareddy** [comment]
There are only two radio buttons. So, there is no need to provide a cancel button to unselect the radio buttons. Also, we are not in a process of modifying the feedback page. Hence differing this issue.

**Comment by BSravanthi** [comment]
Closed #40
