### ISSUE TITLE
QA_Delay Estimation In Chain Of Inverters_Usability_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#43]
Defect Description :
In the home page/landing page of "Delay Estimation In Chain Of Inverters" experiment, an extra header link is present in the page where the extra header link should be removed as it is not required 

Actual Result :
In the home page/landing page of "Delay Estimation In Chain Of Inverters" experiment, an extra header link is present in the page 

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Delay%20Estimation%20In%20Chain%20Of%20Inverters/Delay%20Estimation%20In%20Chain%20Of%20Inverters_01_Usability_smk.org

Attachment:
![39](https://cloud.githubusercontent.com/assets/14869397/14732471/c0c50566-0878-11e6-8231-7e74bbe9a921.png)

**Comment by sadhanareddy** [comment]
issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #43
