### ISSUE TITLE
QA_Delay Estimation In Chain Of Inverters_Usability_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#44]
Defect Description :
In the landing page/home page of "Delay Estimation In Chain Of Inverters" experiment, the name of the experiment is not present in the screen instead the experiment name should be displayed on the screen at the top of the header options 

Actual Result :
In the landing page/home page of "Delay Estimation In Chain Of Inverters" experiment, the name of the experiment is not present in the screen

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Delay%20Estimation%20In%20Chain%20Of%20Inverters/Delay%20Estimation%20In%20Chain%20Of%20Inverters_01_Usability_smk.org

Attachment:
![40](https://cloud.githubusercontent.com/assets/14869397/14732481/cffa02d4-0878-11e6-971e-b0004c486674.png)

**Comment by sadhanareddy** [comment]
issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #44
