### ISSUE TITLE
QA_Schematic Design Of Pass Transistor Logic & Multiplexer_Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#45]
Defect Description :
In the "Schematic Design Of Pass Transistor Logic & Multiplexer" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen inorder to view the list of experiments by the user  

Actual Result :
In the "Schematic Design Of Pass Transistor Logic & Multiplexer" experiment,the back to experiments link is not present in the page

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Schematic%20Design%20Of%20Pass%20Transistor%20Logic%20%26%20Multiplexer/Schematic%20Design%20Of%20Pass%20Transistor%20Logic%20%26%20Multiplexer_35_Back%20to%20experiment_smk.org

Attachment:
![41](https://cloud.githubusercontent.com/assets/14869397/14732488/e135d38e-0878-11e6-86ae-e062a8875b5f.png)

**Comment by sadhanareddy** [comment]
issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #45
