### ISSUE TITLE
QA_System_Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#5]
Defect Description :
In the home page of "VLSI" Lab,when we click on the feedback link it is redirecting to an error page(404) instead feedback page should get opened         

Actual Result :
In the home page of "VLSI" Lab,when we click on the feedback link it is redirecting to an error page(404)   

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/System/System_06_Feedback_smk.org

Attachment:
![1](https://cloud.githubusercontent.com/assets/14869397/14705871/3cf3764a-07d9-11e6-8612-d4cca25a4c9d.png)

**Comment by sadhanareddy** [comment]
issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #5
