### ISSUE TITLE
QA_Schematic Design Of Pass Transistor Logic & Multiplexer_Usability_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#50]
Defect Description :
In the home page/landing page of "Schematic Design Of Pass Transistor Logic & Multiplexer" experiment, an extra header link is present in the page where the extra header link should be removed as it is not required 

Actual Result :
In the home page/landing page of "Schematic Design Of Pass Transistor Logic & Multiplexer" experiment, an extra header link is present in the page 

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Schematic%20Design%20Of%20Pass%20Transistor%20Logic%20%26%20Multiplexer/Schematic%20Design%20Of%20Pass%20Transistor%20Logic%20%26%20Multiplexer_01_Usability_smk.org
Attachment:
![46](https://cloud.githubusercontent.com/assets/14869397/14732531/3890006e-0879-11e6-9403-7548c0a0654f.png)

**Comment by sadhanareddy** [comment]
issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #50
