### ISSUE TITLE
QA_Schematic Design Of Pass Transistor Logic & Multiplexer_Usability_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#51]
Defect Description :
In the landing page/home page of "Schematic Design Of Pass Transistor Logic & Multiplexer" experiment, the name of the experiment is not present in the screen instead the experiment name should be displayed on the screen at the top of the header options 

Actual Result :
In the landing page/home page of "Schematic Design Of Pass Transistor Logic & Multiplexer" experiment, the name of the experiment is not present in the screen

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Schematic%20Design%20Of%20Pass%20Transistor%20Logic%20%26%20Multiplexer/Schematic%20Design%20Of%20Pass%20Transistor%20Logic%20%26%20Multiplexer_01_Usability_smk.org

Attachment:
![47](https://cloud.githubusercontent.com/assets/14869397/14732539/4b9516f4-0879-11e6-9c4e-a78f7b66240d.png)

**Comment by sadhanareddy** [comment]
issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #51
