### ISSUE TITLE
QA_Schematic Design Of Transistor Level XOR & XNOR Gate_Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#54]
Defect Description :
In the feedback page of "Schematic Design Of Transistor Level XOR & XNOR Gate" experiment,the cancel button is not present in the page instead the cancel button should be displayed on the screen as to unselect the selected radio buttons

Actual Result :
In the feedback page of "Schematic Design Of Transistor Level XOR & XNOR Gate" experiment,the cancel button is not present in the page

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Schematic%20Design%20Of%20Transistor%20Level%20XOR%20%26%20XNOR%20Gate/Schematic%20Design%20Of%20Transistor%20Level%20XOR%20%26%20XNOR%20Gate_22_Feedback_smk.org

Attachment:
![50](https://cloud.githubusercontent.com/assets/14869397/14732565/896f2384-0879-11e6-8d97-97aa2c8b2cc6.png)

**Comment by sadhanareddy** [comment]
There are only two radio buttons. So, there is no need to provide a cancel button to unselect the radio buttons. Also, we are not in a process of modifying the feedback page. Hence differing this issue.

**Comment by BSravanthi** [comment]
Close #54
