### ISSUE TITLE
QA_Schematic Design Of Transistor Level XOR & XNOR Gate_Usability_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#56]
Defect Description :
In the home page/landing page of "Schematic Design Of Transistor Level XOR & XNOR Gate" experiment, an extra header link is present in the page where the extra header link should be removed as it is not required 

Actual Result :
In the home page/landing page of "Schematic Design Of Transistor Level XOR & XNOR Gate" experiment, an extra header link is present in the page 

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Schematic%20Design%20Of%20Transistor%20Level%20XOR%20%26%20XNOR%20Gate/Schematic%20Design%20Of%20Transistor%20Level%20XOR%20%26%20XNOR%20Gate_01_Usability_smk.org

Attachment:
![52](https://cloud.githubusercontent.com/assets/14869397/14732578/aacae978-0879-11e6-90c6-e4aa9e552a64.png)

**Comment by sadhanareddy** [comment]
issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #56
