### ISSUE TITLE
QA_Schematic Design Of Transistor Level NAND & NOR Gate_Feedback_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#59]
Defect Description :
In the feedback page of "Schematic Design Of Transistor Level NAND & NOR Gate" experiment,when we click on submit button with out entering the data in the corresponding fields an successful message is displayed on the screen instead an error message should be displayed on the screen as to enter the data in the corresponding fields

Actual Result :
In the feedback page of "Schematic Design Of Transistor Level NAND & NOR Gate" experiment,when we click on submit button with out entering the data in the corresponding fields an successful message is displayed on the screen

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Schematic%20Design%20Of%20Transistor%20Level%20NAND%20%26%20NOR%20Gate/Schematic%20Design%20Of%20Transistor%20Level%20NAND%20%26%20NOR%20Gate_24_Feedback_p1.org

Attachment:
![55](https://cloud.githubusercontent.com/assets/14869397/14732613/f0a85c46-0879-11e6-837b-482188ebc5f9.png)

**Comment by sadhanareddy** [comment]
Issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #59
