### ISSUE TITLE
QA_Layout Design_Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#6]
Defect Description :
In the "Layout Design" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen inorder to view the list of experiments by the user         

Actual Result :
In the "Layout Design" experiment,the back to experiments link is not present in the page   

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Layout%20Design/Layout%20Design_27_Back%20to%20experiment_smk.org

Attachment;
![2](https://cloud.githubusercontent.com/assets/14869397/14705880/51cd0e3c-07d9-11e6-9837-69afbe8b8bba.png)

**Comment by sadhanareddy** [comment]
issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #6
