### ISSUE TITLE
QA_Schematic Design Of Transistor Level NAND & NOR Gate_Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#60]
Defect Description :
In the feedback page of "Schematic Design Of Transistor Level NAND & NOR Gate" experiment,the cancel button is not present in the page instead the cancel button should be displayed on the screen as to unselect the selected radio buttons

Actual Result :
In the feedback page of "Schematic Design Of Transistor Level NAND & NOR Gate" experiment,the cancel button is not present in the page

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Schematic%20Design%20Of%20Transistor%20Level%20NAND%20%26%20NOR%20Gate/Schematic%20Design%20Of%20Transistor%20Level%20NAND%20%26%20NOR%20Gate_22_Feedback_smk.org

Attachment:
![56](https://cloud.githubusercontent.com/assets/14869397/14732620/0805bf6e-087a-11e6-970c-5f4f4de6aa16.png)

**Comment by sadhanareddy** [comment]
There are only two radio buttons. So, there is no need to provide a cancel button to unselect the radio buttons. Also, we are not in a process of modifying the feedback page. Hence differing this issue.

**Comment by BSravanthi** [comment]
Closed #60
