### ISSUE TITLE
QA_Schematic Design Of Transistor Level NAND & NOR Gate_Post-Quiz_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#61]
Defect Description :
In the quiz page of "Schematic Design Of Transistor Level NAND & NOR Gate" experiment, for the post quiz, the cancel button is not present in the page instead the cancel button should be displayed on the screen as to unselect the selected radio buttons

Actual Result :
In the quiz page of "Schematic Design Of Transistor Level NAND & NOR Gate" experiment, for the post quiz, the cancel button is not present in the page

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Schematic%20Design%20Of%20Transistor%20Level%20NAND%20%26%20NOR%20Gate/Schematic%20Design%20Of%20Transistor%20Level%20NAND%20%26%20NOR%20Gate_17_Post-Quiz_p1.org

Attachment:
![57](https://cloud.githubusercontent.com/assets/14869397/14732629/1982f4aa-087a-11e6-9a53-f74f4cc2adf7.png)

**Comment by sadhanareddy** [comment]
Issue is resolved now. Provided a reset button to unselect the radio buttons of the Quiz.

**Comment by BSravanthi** [comment]
Closed #61
