### ISSUE TITLE
QA_Schematic Design Of Transistor Level NAND & NOR Gate_Usability_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#62]
Defect Description :
In the home page/landing page of "Schematic Design Of Transistor Level NAND & NOR Gate" experiment, an extra header link is present in the page where the extra header link should be removed as it is not required 

Actual Result :
In the home page/landing page of "Schematic Design Of Transistor Level NAND & NOR Gate" experiment, an extra header link is present in the page 

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Schematic%20Design%20Of%20Transistor%20Level%20NAND%20%26%20NOR%20Gate/Schematic%20Design%20Of%20Transistor%20Level%20NAND%20%26%20NOR%20Gate_01_Usability_smk.org

Attachment:
![58](https://cloud.githubusercontent.com/assets/14869397/14732637/2d611ae2-087a-11e6-93f3-4f227a49e140.png)

**Comment by sadhanareddy** [comment]
issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #62
