### ISSUE TITLE
QA_Schematic Design Of Transistor Level Inverter_Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#66]
Defect Description :
In the feedback page of "Schematic Design Of Transistor Level Inverter" experiment,the cancel button is not present in the page instead the cancel button should be displayed on the screen as to unselect the selected radio buttons

Actual Result :
In the feedback page of "Schematic Design Of Transistor Level Inverter" experiment,the cancel button is not present in the page

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Schematic%20Design%20Of%20Transistor%20Level%20Inverter/Schematic%20Design%20Of%20Transistor%20Level%20Inverter_22_Feedback_smk.org

Attachment:
![62](https://cloud.githubusercontent.com/assets/14869397/14732662/84ceba5a-087a-11e6-81d7-032e442f5436.png)

**Comment by sadhanareddy** [comment]
There are only two radio buttons.  So,  there is no need to provide a cancel button to unselect the radio buttons.  Also, we are not in a process of modifying the feedback page. Hence differing this issue.

**Comment by BSravanthi** [comment]
Closed #66
