### ISSUE TITLE
QA_Schematic Design Of Transistor Level Inverter_Usability_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#68]
Defect Description :
In the home page/landing page of "Schematic Design Of Transistor Level Inverter" experiment, an extra header link is present in the page where the extra header link should be removed as it is not required

Actual Result :
In the home page/landing page of "Schematic Design Of Transistor Level Inverter" experiment, an extra header link is present in the page 

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Schematic%20Design%20Of%20Transistor%20Level%20Inverter/Schematic%20Design%20Of%20Transistor%20Level%20Inverter_01_Usability_smk.org

Attachment:
![64](https://cloud.githubusercontent.com/assets/14869397/14732675/9ce2616e-087a-11e6-8496-49567a2674dd.png)

**Comment by sadhanareddy** [comment]
issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #68
