### ISSUE TITLE
QA_Schematic Design Of Transistor Level Inverter_Usability_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#69]
Defect Description :
In the landing page/home page of "Schematic Design Of Transistor Level Inverter" experiment, the name of the experiment is not present in the screen instead the experiment name should be displayed on the screen at the top of the header options

Actual Result :
In the landing page/home page of "Schematic Design Of Transistor Level Inverter" experiment, the name of the experiment is not present in the screen

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Schematic%20Design%20Of%20Transistor%20Level%20Inverter/Schematic%20Design%20Of%20Transistor%20Level%20Inverter_01_Usability_smk.org

Attachment:
![65](https://cloud.githubusercontent.com/assets/14869397/14731802/37be01e2-0872-11e6-9cda-7a90756459ba.png)

**Comment by sadhanareddy** [comment]
issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #69
