### ISSUE TITLE
QA_Layout Design_feedback_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#7]
Defect Description :
In the feedback page of "Layout Design" experiment,when we click on submit button with out entering the data in the corresponding fields an successul message is displayed on the screen instead an error message should be displayed on the screen as to enter the data in the corresponding fields       

Actual Result :
In the feedback page of "Layout Design" experiment,when we click on submit button with out entering the data in the corresponding fields an successul message is displayed on the screen   

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Layout%20Design/Layout%20Design_25_feedback_p1.org

Attachment:
![3](https://cloud.githubusercontent.com/assets/14869397/14705895/6a7bf902-07d9-11e6-8c45-c02769f2c07d.png)

**Comment by sadhanareddy** [comment]
issue is resolved now

**Comment by BSravanthi** [comment]
Closed #7
