### ISSUE TITLE
Broken links in the Pre Quiz page

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/vlsi-iiith#70]
In the **Schematic Design Of D-Latch and D-Flip Flop lab,** when we click on "Introduction, Objective, Theory, Procedure, Simulator, Quiz, References, Feedback" links in the page "Start the Quiz" of Simulator page the page is redirecting to an Error page. Instead it should re direct to the appropriate page.

**Comment by sadhanareddy** [comment]
Issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #70
