### ISSUE TITLE
QA_Layout Design_feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#8]
Defect Description :
In the feedback page of "Layout Design" experiment,the cancel button is not present in the page instead the cancel button should be displayed on the screen as to unselect the selected radio buttons       

Actual Result :
In the feedback page of "Layout Design" experiment,the cancel button is not present in the page   

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Layout%20Design/Layout%20Design_22_feedback_smk.org

Attachment:
![4](https://cloud.githubusercontent.com/assets/14869397/14705934/a7b97e7a-07d9-11e6-9456-200a5265b658.png)

**Comment by sadhanareddy** [comment]
There are only two radio buttons. So, there is no need to provide a cancel button to unselect the radio buttons. Also, we are not in a process of modifying the feedback page. Hence differing this issue.

**Comment by BSravanthi** [comment]
Closed #8
