### ISSUE TITLE
QA_Layout Design_Post-Quiz_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/vlsi-iiith#9]
Defect Description :
In the quiz page of "Layout Design" experiment, for the post quiz, the cancel button is not present in the page instead the cancel button should be displayed on the screen as to unselect the selected radio buttons       

Actual Result :
In the quiz page of "Layout Design" experiment, for the post quiz, the cancel button is not present in the page   

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/lsi-iiith/blob/master/test-cases/integration_test-cases/Layout%20Design/Layout%20Design_17_Post-Quiz_p1.org

Attachment:
![5](https://cloud.githubusercontent.com/assets/14869397/14705962/c2f41f24-07d9-11e6-99a6-1fa1ca2e70bf.png)

**Comment by sadhanareddy** [comment]
Issue is resolved now. Provided a reset button to unselect the radio buttons of the Quiz.

**Comment by BSravanthi** [comment]
Closed #9
