### ISSUE TITLE
QA_VLSI_ Schematic Design Of Pass Transistor Logic & Multiplexer_Experiment_not-ported-properly

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/vlsi-iiith#95]
Defect Description :
In the experiment section of Schematic Design Of Pass Transistor Logic & Multiplexer experiment, Instead of porting the experiment, a link which navigates to vlabs page has been given.

Actual Result :
In the experiment section of Schematic Design Of Pass Transistor Logic & Multiplexer experiment, Instead of porting the experiment, a link which navigates to vlabs page has been given.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
Not available

**Comment by BSravanthi** [comment]
Removed the link and ported the experiment using Iframe tool. Ported both the experiments in separate units.

**Comment by sravanthimodepu** [comment]
Closing.
